### ISSUE TITLE
multiprocessing.pool.MaybeEncodingError: Error sending result ~~

### ISSUE THREAD

**Issue by hmkim** [crosenth/medirect#1]
Could you check this problem?

<img width="1432" alt="screenshot 2017-03-14 10 50 35" src="https://cloud.githubusercontent.com/assets/4966343/23882461/1449204c-08a4-11e7-8818-c92c99097332.png">

With this command,
 time mefetch -id create_targetList -proc 80  -mode text -format fasta -db nucleotide > create_targetList.fa

Thanks in advance!

**Comment by crosenth** [comment]
Hi hmkim,

So sorry I missed your Issue!  The Github Issue obvi got lost in my Inbox.

My thought is that the NCBI server responded with a bad result and if you were to try it again using the exact same command it might work fine.  You can also increase the log verbosity ``-v``.  In the latest release I cleaned up the logging a bit.  The NCBI servers can sometimes be unpredictable.  

If not and you are still having issues maybe you can send me some example input ``-id create_targetList`` that I can try out and debug from.

Thanks for your note!  Let me know!

Chris

**Comment by hmkim** [comment]
Thanks, I'll try it with verbosity option.
